---
- name: Ping the nodes
  hosts: all
  become: true
  gather_facts: false
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:
   - name: Print message
     ansible.builtin.debug:
      msg: "Hello World"
